syntax enable
set mouse=a
set nocompatible
set background=dark
set cpoptions=aABceFsmq
filetype plugin indent on
set autochdir
set backspace=indent,eol,start
set fileformats=unix,mac,dos
set iskeyword+=_,$,@,%,#
set noerrorbells
set whichwrap=b,s,h,l,<,>,~,[,]
set wildmenu
set cursorcolumn
set cursorline
set incsearch
set laststatus=2
set linespace=0
set list
set listchars=tab:>-,trail:-
set matchtime=5
set number
set numberwidth=5
set report=0
set ruler
set scrolloff=10
set showcmd
set showmatch
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]%{fugitive#statusline()}
set expandtab
set formatoptions=rq
set ignorecase
set infercase
set nowrap
set smartcase
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=8
set foldenable
set foldmarker={,}
set foldmethod=marker
set foldlevel=100
set foldopen=block,hor,mark,percent,quickfix,tag
set autoread
runtime macros/matchit.vim

let perl_extended_vars=1
let b:match_ignorecase = 1
let g:go_version_warning = 0
let g:indent_guides_guide_size = 1
let g:indent_guides_color_change_percent = 3
let g:indent_guides_enable_on_vim_startup = 1

autocmd vimenter * NERDTree | wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

nmap ,bf !!boxes -d tjc -s 75<CR>
vmap ,bf !boxes -d tjc -s 75<CR>
nmap ,bx !!boxes -a c -d shell -s 40<CR>
vmap ,bx !boxes -a c -d shell -s 40<CR>
let mapleader = ','
let NERDTreeWinPos = 'right'
let NERDTreeMinimalUI=1
let NERDChristmasTree=1
let g:pyflakes_use_quickfix = 0
let g:pep8_map='<leader>8'
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview
map <leader>n :NERDTreeToggle<CR>
map <C-t><up> :tabr<cr>
map <C-t><down> :tabl<cr>
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>

let g:airline_powerline_fonts = 1
set wildignore+=*/tmp/*,*.so,*.swp,*.zip

augroup reload_vimrc " {
        autocmd!
            autocmd BufWritePost $MYVIMRC source $MYVIMRC
        augroup END " }

nnoremap <silent> <Leader>df :call DiffToggle()<CR>

function! DiffToggle()
    if &diff
        diffoff
    else
        diffthis
    endif
:endfunction

" Git commits.
autocmd FileType gitcommit setlocal spell
autocmd FileType python set expandtab
vmap Q gq
nmap Q gqap
:set diffopt=iwhite
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin('~/.vim/plugged')

Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/scrooloose/nerdtree-git-plugin.git'
Plug 'junegunn/vim-easy-align'
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
Plug 'vim-scripts/indentpython.vim'
Plug 'jmcantrell/vim-virtualenv'
Plug 'godlygeek/tabular'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf'
Plug 'chase/vim-ansible-yaml'
Plug 'b4b4r07/vim-ansible-vault'
Plug 'jamessan/vim-gnupg'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'tomtom/tcomment_vim'
Plug 'easymotion/vim-easymotion'
Plug 'dhruvasagar/vim-table-mode'
Plug 'pearofducks/ansible-vim'
" Plug 'Valloric/YouCompleteMe'

" Initialize plugin system
call plug#end()

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')
call NERDTreeHighlightFile('rb', 'Magenta', 'none', '#ff00ff', '#151515')
call NERDTreeHighlightFile('sh', 'Red', 'none', '#ff00ff', '#151515')
map ; :FZF<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd BufEnter * lcd %:p:h
map <leader>r :NERDTreeFind<cr>
map <C-o> :NERDTreeToggle %<CR>



" END
